/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    'Facceso.php',
    'ValidaAcceso.php',
    'menu/MenuA.php',
    'menu/MenuU.php',
    'conductores/FConductores.php',
    'conductores/SConductores.php',
    'conductores/IConductores.php',
    'conductores/UConductores.php',
    'conductores/DConductores.php',
    'licencias/FLicencias.php',
    'licencias/Dlicencias.php',
    'licencias/Ilicencias.php',
    'licencias/ULicencias.php',
    'licencias/SLicencias.php',
    'multas/IMultas.php',
    'multas/DMultas.php',
    'multas/FMultas.php',
    'multas/UMultas.php',
    'multas/SMultas.php',
    'oficiales/FOficiales.php',
    'oficiales/SOficiales.php',
    'oficiales/IOficiales.php',
    'oficiales/UOficiales.php',
    'oficiales/DOficiales.php',
    'propietarios/FPropietarios.php',
    'propietarios/SPropietarios.php',
    'propietarios/IPropietarios.php',
    'propietarios/UPropietarios.php',
    'propietarios/DPropietarios.php',
    'tarjetas/FTarjetas.php',
    'tarjetas/STarjetas.php',
    'tarjetas/UTarjetas.php',
    'tarjetas/ITarjetas.php',
    'tarjetas/DTarjetas.php',
    'vehiculos/FVehiculos.php',
    'vehiculos/SVehiculos.php',
    'vehiculos/IVehiculos.php',
    'vehiculos/UVehiculos.php',
    'vehiculos/DVehiculos.php',
    'verificaciones/UVerificaciones.php',
    'verificaciones/SVerificaciones.php',
    'verificaciones/DVerificaciones.php',
    'verificaciones/IVerificaciones.php',
    'verificaciones/FVerificaciones.php',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
